# Change these first
owner: JonasSchaber
repo: uptime

sites:
  - name: IServ
    url: https://gymall.de/iserv/
    icon: https://www.gymall.de/favicon.ico
  - name: Moodle
    url: moodle.gymall.de
  - name: Homepage
    url: gymnasium-allermoehe.hamburg.de
  - name: Kunstgalerie
    url: gymnasium-allermoehe.info  
  - name: Google
    url: https://www.google.com/
    icon: https://www.google.com/favicon.ico
    
  
status-website:
  
  name: Your Status Website
  theme: light
  cname: http://multisite.gymnasium-allermoehe.info/system-status-new/
  
