# Change these first
owner: JonasSchaber
repo: uptime

sites:
  - name: IServ
    url: https://gymall.de/iserv/
  - name: Moodle
    url: moodle.gymall.de
  - name: Homepage
    url: gymnasium-allermoehe.hamburg.de
  - name: Kunstgalerie
    url: gymnasium-allermoehe.info  
  - name: Google
    url: https://www.google.com/  
    
  
status-website:
  
  baseUrl: /uptime
  name: Your Status Website
  
