# Change these first
owner: JonasSchaber
repo: uptime

sites:
  - name: IServ
    url: https://gymall.de/iserv/
    icon: https://www.gymall.de/favicon.ico
  - name: Moodle
    url: moodle.gymall.de
    icon: https://moodle.gymall.de/theme/image.php/boost/theme/1642061074/favicon
  - name: Homepage
    url: gymnasium-allermoehe.hamburg.de
    icon: https://gymnasium-allermoehe.hamburg.de/wp-content/uploads/sites/16/2018/02/cropped-GymAll-Icon-32x32.png
  - name: Kunstgalerie
    url: https://it.gymall.de/kunst/
    icon: https://www.gymall.de/favicon.ico
  - name: test broke
    url: https://hms-studios.de/
    
  

  
  
    
  
status-website:
  baseUrl: /uptime
  name: System Status Gymnasium Allermöhe
  theme: light
  
  
  
