# Change these first
owner: JonasSchaber
repo: uptime

sites:
  - name: IServ
    url: https://gymall.de/iserv/
  - name: Moodle
    url: https://moodle.gymall.de/
  - name: Homepage
    url: https://gymnasium-allermoehe.hamburg.de/
  - name: Kunstgalerie
    url: https://gymnasium-allermoehe.info/  
  
status-website:
  
  baseUrl: /uptime
  name: Your Status Website
  
